services:
  mongo:
    image: mongo
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      - ./data/mongo:/data/db
      - ./config/mongo:/etc/mongo-init
    environment:
      USER_NAME: ${USER_NAME:-admin}
      USER_PASSWORD: ${USER_PASSWORD:-admin}

    command: ['sh', '/etc/mongo-init/init.sh']

  valkey:
    image: valkey/valkey:8.1.3
    ports:
      - '127.0.0.1:6379:6379'
    environment:
      USER_NAME: ${USER_NAME:-admin}
      USER_PASSWORD: ${USER_PASSWORD:-admin}

    volumes:
      - ./data/valkey:/data
      - ./config/valkey:/usr/local/etc/valkey
    command: ['sh', '/usr/local/etc/valkey/start.sh']
